version: "3.8"

services:
  # Removing mailpit in production
  mailpit:
    deploy:
      replicas: 0

  backend:
    user: root
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  worker:
    command: ["celery", "-A", "app.core.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  scheduler:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ws_manager:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
