"""initial_schema

Revision ID: 0e9ba3c1ea8d
Revises: 
Create Date: 2026-04-26 07:39:42.180812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e9ba3c1ea8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS citext;')
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto;')
    
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_verification_token_hash', sa.String(), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token_hash', sa.String(), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret_encrypted', postgresql.BYTEA(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.String(), nullable=True),
    sa.Column('suspended_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['suspended_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_account_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impersonating', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    # Set append-only enforcement on audit_log for the application role
    op.execute('REVOKE UPDATE, DELETE ON audit_log FROM app;')
    
    # Create required indices manually if they were missed by autogenerate
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_role ON users(role) WHERE deleted_at IS NULL;")
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_suspended ON users(suspended_at) WHERE suspended_at IS NOT NULL;")
    op.execute("CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id) WHERE revoked_at IS NULL;")
    op.execute("CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor_user_id, occurred_at DESC);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_log(target_user_id, occurred_at DESC);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log(action, occurred_at DESC);")

    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop indices
    op.execute("DROP INDEX IF EXISTS idx_audit_action;")
    op.execute("DROP INDEX IF EXISTS idx_audit_target;")
    op.execute("DROP INDEX IF EXISTS idx_audit_actor;")
    op.execute("DROP INDEX IF EXISTS idx_sessions_user;")
    op.execute("DROP INDEX IF EXISTS idx_users_suspended;")
    op.execute("DROP INDEX IF EXISTS idx_users_role;")

    op.execute('GRANT UPDATE, DELETE ON audit_log TO app;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
