"""add_missing_account_columns

Revision ID: 7f35e75d56cf
Revises: bb1234567890
Create Date: 2026-04-26 20:01:40.739526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f35e75d56cf'
down_revision: Union[str, None] = 'bb1234567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('baskets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bo_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('bo_margin', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('grid_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sos_filled', sa.Integer(), nullable=False),
    sa.Column('avg_entry', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('notional_total', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('tp_target_usd', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('tp_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('funding_paid', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('fees_paid', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baskets_account_id'), 'baskets', ['account_id'], unique=False)
    op.create_index(op.f('ix_baskets_user_id'), 'baskets', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('basket_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('binance_order_id', sa.BigInteger(), nullable=True),
    sa.Column('binance_client_order_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('commission_asset', sa.String(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binance_client_order_id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_basket_id'), 'orders', ['basket_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.add_column('accounts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('accounts', sa.Column('auto_trade_enabled', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_accounts_api_key_hash'), table_name='accounts')
    op.create_index(op.f('ix_accounts_api_key_hash'), 'accounts', ['api_key_hash'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_audit_action'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_actor'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_target'), table_name='audit_log')
    op.alter_column('equity_snapshots', 'wallet_balance',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equity_snapshots', 'total_equity',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equity_snapshots', 'unrealized_pnl',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equity_snapshots', 'margin_used',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_equity_snapshots_account_id'), 'equity_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_equity_snapshots_user_id'), 'equity_snapshots', ['user_id'], unique=False)
    op.alter_column('events', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.create_index(op.f('ix_events_account_id'), 'events', ['account_id'], unique=False)
    op.create_index('ix_events_severity_occurred', 'events', ['severity', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_sessions_user'), table_name='sessions', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('idx_users_role'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_users_suspended'), table_name='users', postgresql_where='(suspended_at IS NOT NULL)')
    op.drop_column('users', 'force_password_reset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('force_password_reset', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_users_suspended'), 'users', ['suspended_at'], unique=False, postgresql_where='(suspended_at IS NOT NULL)')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_sessions_user'), 'sessions', ['user_id'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index('ix_events_severity_occurred', table_name='events')
    op.drop_index(op.f('ix_events_account_id'), table_name='events')
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.alter_column('events', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_equity_snapshots_user_id'), table_name='equity_snapshots')
    op.drop_index(op.f('ix_equity_snapshots_account_id'), table_name='equity_snapshots')
    op.alter_column('equity_snapshots', 'margin_used',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equity_snapshots', 'unrealized_pnl',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equity_snapshots', 'total_equity',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('equity_snapshots', 'wallet_balance',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_audit_target'), 'audit_log', ['target_user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_actor'), 'audit_log', ['actor_user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_log', ['action', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_api_key_hash'), table_name='accounts')
    op.create_index(op.f('ix_accounts_api_key_hash'), 'accounts', ['api_key_hash'], unique=True)
    op.drop_column('accounts', 'auto_trade_enabled')
    op.drop_column('accounts', 'user_id')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_basket_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_baskets_user_id'), table_name='baskets')
    op.drop_index(op.f('ix_baskets_account_id'), table_name='baskets')
    op.drop_table('baskets')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
