"""Core enums for the TWIN GRID Console platform."""

from enum import Enum


class Role(str, Enum):
    """User roles for RBAC."""

    USER = "USER"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"


class WorkspaceRole(str, Enum):
    """Workspace membership roles."""

    OWNER = "OWNER"
    ADMIN = "ADMIN"
    VIEWER = "VIEWER"


class AccountStatus(str, Enum):
    """Binance account lifecycle states."""

    IDLE = "IDLE"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    HALTED = "HALTED"


class BasketStatus(str, Enum):
    """Basket lifecycle states."""

    OPENING = "OPENING"
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    LIQUIDATED = "LIQUIDATED"
    ERROR = "ERROR"


class AuditAction(str, Enum):
    """All auditable actions per §16.1."""

    # Auth
    USER_REGISTERED = "USER_REGISTERED"
    USER_VERIFIED = "USER_VERIFIED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"
    EMAIL_CHANGED = "EMAIL_CHANGED"
    TOTP_ENROLLED = "TOTP_ENROLLED"
    TOTP_DISABLED = "TOTP_DISABLED"
    # Account
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    ACCOUNT_DELETED = "ACCOUNT_DELETED"
    ACCOUNT_STARTED = "ACCOUNT_STARTED"
    ACCOUNT_PAUSED = "ACCOUNT_PAUSED"
    ACCOUNT_HALTED = "ACCOUNT_HALTED"
    ACCOUNT_EMERGENCY_CLOSE = "ACCOUNT_EMERGENCY_CLOSE"
    SETTINGS_CHANGED = "SETTINGS_CHANGED"
    # Basket
    BASKET_OPENED = "BASKET_OPENED"
    BASKET_CLOSED_TP = "BASKET_CLOSED_TP"
    BASKET_LIQUIDATED = "BASKET_LIQUIDATED"
    # Admin
    USER_SUSPENDED = "USER_SUSPENDED"
    USER_UNSUSPENDED = "USER_UNSUSPENDED"
    USER_FORCE_LOGOUT = "USER_FORCE_LOGOUT"
    USER_FORCE_PASSWORD_RESET = "USER_FORCE_PASSWORD_RESET"
    USER_PROMOTED = "USER_PROMOTED"
    USER_DEMOTED = "USER_DEMOTED"
    USER_HARD_DELETED = "USER_HARD_DELETED"
    IMPERSONATION_STARTED = "IMPERSONATION_STARTED"
    IMPERSONATION_ENDED = "IMPERSONATION_ENDED"
    PLATFORM_HALT = "PLATFORM_HALT"
    ENCRYPTION_KEY_ROTATED = "ENCRYPTION_KEY_ROTATED"
    TRADING_ENABLED = "TRADING_ENABLED"
    TRADING_DISABLED = "TRADING_DISABLED"
    AUTO_TRADE_TOGGLED = "AUTO_TRADE_TOGGLED"
    # Fee & Wallet
    DEPOSIT_SUBMITTED = "DEPOSIT_SUBMITTED"
    DEPOSIT_APPROVED = "DEPOSIT_APPROVED"
    DEPOSIT_REJECTED = "DEPOSIT_REJECTED"
    FEE_DEDUCTED = "FEE_DEDUCTED"
    BALANCE_ADJUSTED = "BALANCE_ADJUSTED"
    FEE_SETTINGS_CHANGED = "FEE_SETTINGS_CHANGED"
    AFFILIATE_TRANSFERRED = "AFFILIATE_TRANSFERRED"
    # Subscription
    SUBSCRIPTION_CHANGED = "SUBSCRIPTION_CHANGED"
    SUBSCRIPTION_RENEWED = "SUBSCRIPTION_RENEWED"
    SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"
    SUBSCRIPTION_FAILED = "SUBSCRIPTION_FAILED"


class FeeTransactionType(str, Enum):
    """Types of fee/balance transactions."""

    FEE_DEDUCTION = "FEE_DEDUCTION"
    DEPOSIT = "DEPOSIT"
    ADMIN_CREDIT = "ADMIN_CREDIT"
    ADMIN_DEBIT = "ADMIN_DEBIT"
    AFFILIATE_COMMISSION = "AFFILIATE_COMMISSION"
    SUBSCRIPTION_CHARGE = "SUBSCRIPTION_CHARGE"
    AFFILIATE_TRANSFER = "AFFILIATE_TRANSFER"


class DepositStatus(str, Enum):
    """Deposit request lifecycle states."""

    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


class EventSeverity(str, Enum):
    """System event severity levels."""

    DEBUG = "DEBUG"
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
